[versions]
firstspirit-runtime = "5.2.241109"
slf4j-api = "2.0.16"

[libraries]
firstspirit-runtime = { module = "de.espirit.firstspirit:fs-isolated-runtime", version.ref = "firstspirit-runtime" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j-api" }
